/// <reference types="vite-envs/client" />
/// <reference types="vite/client" />
/// <reference types="vite-plugin-pwa/info" />
/// <reference types="vite-plugin-pwa/vanillajs" />

type ImportMetaEnv = {
  // Auto-generated by `npx vite-envs update-types` and hot-reloaded by the `vite-env` plugin
  // You probably want to add `/src/vite-env.d.ts` to your .prettierignore
  BASE_URL: string
  MODE: string
  DEV: boolean
  PROD: boolean
  BUILD_TIME: number
  VERSION: string
  API_BASE_URL: string
  HUNT_START_TIME: string
  HUNT_END_TIME: string
  HOME_TEAM_API_ID: string
  GROUP_WALKING_ID: string
  GROUP_CAR_ID: string
  GROUP_MOTORCYCLE_ID: string
  GROUP_BIKE_ID: string
  DISCORD_URL: string
  LOGO_URL: string
  GROUP_NAME: string
  TEAMS_AREA_EDITING: string
  // @user-defined-start
  /*
   *  You can use this section to explicitly extend the type definition of `import.meta.env`
   *  This is useful if you're using Vite plugins that define specific `import.meta.env` properties.
   *  If you're not using such plugins, this section should remain as is.
   */
  SSR: boolean;
  // @user-defined-end
}

interface ImportMeta {
  // Auto-generated by `npx vite-envs update-types`

  url: string

  readonly hot?: import('vite-envs/types/hot').ViteHotContext

  readonly env: ImportMetaEnv

  glob: import('vite-envs/types/importGlob').ImportGlobFunction
}
